name: "snyk test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install snyk delta
        run: npm install --location=global snyk-delta
      - uses: snyk/actions/python-3.7@master
      - name: Snyk Test
        run: snyk test --json --print-deps | snyk-delta --baselineOrg --orgID 39e138ee-1e91-4197-9c08-31d4b6fc07a7 --baselineProject 2188c10e-f254-4b0c-8533-66ea8645887a
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
