name: "snyk test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install snyk + snyk delta
        run: |
          npm install --location=global snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          npm install --location=global snyk-delta
          which python3
      - name: Snyk Delta Test
        run: snyk test --json --print-deps --command=/opt/hostedtoolcache/Python/3.10.7/x64/bin/python3 --file=requirements.txt | snyk-delta
