name: "snyk test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install snyk + snyk delta
        run: |
          npm install --location=global snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          npm install --location=global snyk-delta
      - name: Snyk Delta Test
        run: snyk test --json --print-deps | snyk-delta
